version: '2'
services:
  eureka-service:
    build: eureka-service
    image: eureka-service
    ports:
      - 8761:8761
  test-service:
    build: test-service
    image: test-service
    ports:
      - 1001:1001
  test-service2:
    build: test-service2
    image: test-service2
    ports:
      - 1002:1002