version: '2'
services:
  eureka-service:
    build: eureka-service
    image: eureka-service
    ports:
      - 8761:8761
  hystrix-service:
    build: hystrix-service
    image: hystrix-service
    ports:
      - 8282:8282
  test-service:
    build: test-service
    image: test-service
    ports:
      - 1234:1234
