spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

---

spring:
  profiles: docker
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false