spring:
  profiles:
    active: "dev"
    
---

spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
endpoints:
  prometheus:
    enabled: true
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
endpoints:
  prometheus:
    enabled: true



